name: Test docker image
on: pull_request
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build --tag cloud-init .
    - name: Run image
      run: |
        docker run -d -p 80:80 cloud-init
        sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
